capture_controllers:
    resource:
        path: ../src/Capture/Controller/
        namespace: App\Capture\Controller
    type: attribute

design_controllers:
    resource:
        path: ../src/Design/Controller/
        namespace: App\Design\Controller
    type: attribute

home_controllers:
    resource:
        path: ../src/Home/Controller/
        namespace: App\Home\Controller
    type: attribute

global_controllers:
    resource:
        path: ../src/Global/Controller/
        namespace: App\Global\Controller
    type: attribute